# backend/app/agents/errors.py
from enum import Enum


class ErrorCode(str, Enum):
    LOCATION_DRIFT = "LOCATION_DRIFT"
    GEOCODE_FAILED = "GEOCODE_FAILED"
    MISSING_LOCATION = "MISSING_LOCATION"
    DATA_PARSE_FAILED = "DATA_PARSE_FAILED"
    TOOL_EXECUTION_ERROR = "TOOL_EXECUTION_ERROR"
    TOOL_NOT_IMPLEMENTED = "TOOL_NOT_IMPLEMENTED"
    SANDBOX_TIMEOUT = "SANDBOX_TIMEOUT"
    SANDBOX_OOM = "SANDBOX_OOM"
    SANDBOX_FORBIDDEN_IMPORT = "SANDBOX_FORBIDDEN_IMPORT"
    CHECKPOINTER_NOT_FOUND = "CHECKPOINTER_NOT_FOUND"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    INVALID_TOOL_CALL = "INVALID_TOOL_CALL"
    REFINE_LIMIT_EXCEEDED = "REFINE_LIMIT_EXCEEDED"
    LLM_RESPONSE_PARSE_FAILED = "LLM_RESPONSE_PARSE_FAILED"
    INVALID_PARAMS = "INVALID_PARAMS"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"


class ToolCallError(Exception):
    def __init__(self, code: ErrorCode, message: str):
        self.code = code
        self.message = message
        super().__init__(f"[{code.value}] {message}")
